/**
* Recipe Puppy
* Recipe Puppy
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.internal.CommonEnumSerializer

/**
 * 
 * @param href 
 * @param title 
 * @param ingredients 
 * @param thumbnail 
 */
@Serializable
data class Recipe (
    @SerialName(value = "href") @Required val href: kotlin.String,
    @SerialName(value = "title") val title: kotlin.String? = null,
    @SerialName(value = "ingredients") val ingredients: kotlin.String? = null,
    @SerialName(value = "thumbnail") val thumbnail: kotlin.String? = null
)

