/**
* Recipe Puppy
* Recipe Puppy
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.Recipe

import kotlinx.serialization.*
import kotlinx.serialization.internal.CommonEnumSerializer

/**
 * 
 * @param title 
 * @param results 
 */
@Serializable
data class RecipeList (
    @SerialName(value = "title") val title: kotlin.String? = null,
    @SerialName(value = "results") val results: kotlin.collections.List<Recipe>? = null
)

